# Generated by Django 5.1.7 on 2025-04-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viewovo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
            ],
        ),
    ]
