# Generated by Django 5.1.7 on 2025-05-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewovo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoreoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('sitio_toma', models.CharField(max_length=255, verbose_name='Sitio de Toma')),
                ('ph', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='pH (6.5 a 9.0)')),
                ('cloro_residual', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cloro Residual (ppm)')),
                ('dureza', models.IntegerField(verbose_name='Dureza (ppm < 250)')),
                ('adicion_cloro', models.IntegerField(blank=True, null=True, verbose_name='Adición Cloro Cantidad (Un)')),
                ('vigencia_reactivos', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vigencia de Reactivos')),
                ('responsable', models.CharField(max_length=255, verbose_name='Responsable')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
        ),
    ]
