# Generated by Django 5.1.7 on 2025-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewovo', '0002_monitoreoagua'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreoagua',
            name='lote',
            field=models.CharField(default=1, max_length=100, verbose_name='Lote'),
            preserve_default=False,
        ),
    ]
